# Generated by Django 3.0.2 on 2020-01-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('wallet_balance', models.IntegerField(default=0)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=True)),
                ('has_ordered_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('is_vendor', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_complete', models.BooleanField(default=False)),
                ('cost', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.SoldItem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.SoldItem')),
            ],
        ),
    ]
