# Generated by Django 3.0.2 on 2020-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
