# Generated by Django 3.0.2 on 2020-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_auto_20200123_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='order_history',
            field=models.FileField(default='null', upload_to='', verbose_name='reports/'),
            preserve_default=False,
        ),
    ]
