# Generated by Django 3.0.2 on 2020-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_vendor_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='order_history',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
