# Generated by Django 3.0.2 on 2020-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_auto_20200124_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='order_history',
            field=models.FileField(upload_to='images/'),
        ),
    ]
