from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Index, name='Index'),
    path('CustomerSignUp', views.CustomerSignUp, name='CustomerSignUp'),
    path('CustomerLogin', views.CustomerLogin, name='CustomerLogin'),
    path('CreateCustomer', views.CreateCustomer, name='CreateCustomer'),
    path('FindCustomer', views.FindCustomer, name='FindCustomer'),
    path('VendorSignUp', views.VendorSignUp, name='VendorSignUp'),
    path('VendorLogin', views.VendorLogin, name='VendorLogin'),
    path('CreateVendor', views.CreateVendor, name='CreateVendor'),
    path('FindVendor', views.FindVendor, name='FindVendor'),
    path('Logout', views.Logout, name='Logout'),
    path('CustomerHome', views.CustomerHome, name='CustomerHome'),
    path('VendorHome', views.VendorHome, name='VendorHome'),
    path('AddItemToCart', views.AddItemToCart, name='AddItemToCart'),
    path('BuyItem', views.BuyItem, name='BuyItem'),
    path('Cart', views.Cart, name='Cart'),
    path('AddItemToSell', views.AddItemToSell, name='AddItemToSell'),
    path('AddItemInfo', views.AddItemInfo, name='AddItemInfo'),
    path('DeleteItem', views.DeleteItem, name='DeleteItem'),
    path('Cart', views.Cart, name='Cart'),
    path('RemoveFromCart', views.RemoveFromCart, name='RemoveFromCart'),
    path('AddMoney', views.AddMoney, name='AddMoney'),
    path('ChangeAddress', views.ChangeAddress, name='ChangeAddress'),
    path('CustomerOrderHistory', views.CustomerOrderHistory, name='CustomerOrderHistory'),
    path('CompleteOrder', views.CompleteOrder, name='CompleteOrder'),
    path('ModifyCustomerProfilePicture', views.ModifyCustomerProfilePicture, name='ModifyCustomerProfilePicture'),
    path('ModifyVendorProfilePicture', views.ModifyVendorProfilePicture, name='ModifyVendorProfilePicture'),
    path('ViewOrders', views.ViewOrders, name='ViewOrders'),
    path('Home', views.Home, name='Home'),
    path('FindUser', views.FindUser, name='FindUser'),
    path('CreateGoogleCustomer', views.CreateGoogleCustomer, name='CreateGoogleCustomer'),
    path('CreateGoogleVendor', views.CreateGoogleVendor, name='CreateGoogleVendor'),
    path('GenerateReport', views.GenerateReport, name='GenerateReport'),
    path(r'^export/xls/$', views.GenerateReport, name='export_orders_xls'),
]